{% set version = '2.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crochet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crochet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crochet/crochet_{{ version }}.tar.gz
  sha256: d843444bec547a6c691631931bc68b47c1572bc8935242c992d982cd8c53727f

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('crochet')"           # [not win]
    - "\"%R%\" -e \"library('crochet')\""  # [win]

about:
  home: https://github.com/agrueneberg/crochet
  license: MIT
  summary: Functions to help implement the extraction / subsetting / indexing function '[' and
    replacement function '[<-' of custom matrix-like types (based on S3, S4, etc.),
    modeled as closely to the base matrix class as possible (with tests to prove it).
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: crochet
# Version: 2.3.0
# License: MIT + file LICENSE
# Title: Implementation Helper for '[' and '[<-' of Custom Matrix-Like Types
# Description: Functions to help implement the extraction / subsetting / indexing function '[' and replacement function '[<-' of custom matrix-like types (based on S3, S4, etc.), modeled as closely to the base matrix class as possible (with tests to prove it).
# Authors@R: person("Alexander", "Grueneberg", email = "cran@agrueneberg.info", role = c("aut", "cre"))
# URL: https://github.com/agrueneberg/crochet
# BugReports: https://github.com/agrueneberg/crochet/issues
# Depends: R (>= 3.0.0)
# Imports: methods
# Suggests: tinytest, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-05-19 21:15:31 UTC; agrueneberg
# Author: Alexander Grueneberg [aut, cre]
# Maintainer: Alexander Grueneberg <cran@agrueneberg.info>
# Repository: CRAN
# Date/Publication: 2020-05-20 22:40:02 UTC
